name: Deploy

on:
  push:
    branches: ['main']

jobs:
  build-on-vps:
    runs-on: ubuntu-latest
    steps:
      - name: SSH into VPS and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            set -e
            cd /srv/website
            cd app
            git fetch --depth=1 origin main
            git checkout -f main
            git reset --hard origin/main
            cd ..
            docker compose build --pull web
            docker compose up -d --remove-orphans
            docker image prune -f
